name: Fetch LeetCode Daily Question

on:
  schedule:
    - cron: '5 1 * * *'  # every day at 6:35 AM IST
  workflow_dispatch:

jobs:
  daily-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install requests

    - name: Run script
      run: python leetcode_daily.py

    - name: Commit and Push
      run: |
        git config --global user.name 'Your Name'
        git config --global user.email 'you@example.com'
        git add .
        git commit -m "Update daily question" || echo "Nothing to commit"
        git push
